{
	"id": "RHSA-2021:1608",
	"advisories": [
		{
			"content": {
				"id": "RHSA-2021:1608",
				"title": "RHSA-2021:1608: python-cryptography security, bug fix, and enhancement update (Moderate)",
				"description": "The python-cryptography packages contain a Python Cryptographic Authority's (PyCA's) cryptography library, which provides cryptographic primitives and recipes to Python developers.\n\nThe following packages have been upgraded to a later upstream version: python-cryptography (3.2.1). (BZ#1873581, BZ#1891947)\n\nSecurity Fix(es):\n\n* python-cryptography: bleichenbacher timing oracle attack against RSA decryption (CVE-2020-25659)\n\n* python-cryptography: certain sequences of update() calls when symmetrically encrypting very large payloads could result in an integer overflow and lead to buffer overflows (CVE-2020-36242)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.4 Release Notes linked from the References section.",
				"severity": [
					{
						"type": "vendor",
						"source": "secalert@redhat.com",
						"vendor": "Moderate"
					}
				],
				"references": [
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/errata/RHSA-2021:1608"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/security/cve/CVE-2020-25659"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/security/cve/CVE-2020-36242"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://bugzilla.redhat.com/1889988"
					},
					{
						"source": "secalert@redhat.com",
						"url": "https://bugzilla.redhat.com/1926226"
					}
				],
				"published": "2021-05-18T00:00:00Z",
				"modified": "2021-05-18T00:00:00Z"
			},
			"segments": [
				{
					"ecosystem": "redhat:8",
					"tag": "rhel-8-including-unpatched"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-25659",
				"severity": [
					{
						"type": "vendor",
						"source": "secalert@redhat.com",
						"vendor": "moderate"
					},
					{
						"type": "cvss_v31",
						"source": "secalert@redhat.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
							"base_score": 5.9,
							"base_severity": "MEDIUM",
							"temporal_score": 5.9,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.9,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "secalert@redhat.com",
						"cwe": [
							"CWE-385"
						]
					}
				],
				"references": [
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/security/cve/CVE-2020-25659"
					}
				],
				"published": "2020-10-25T00:00:00Z"
			},
			"segments": [
				{
					"ecosystem": "redhat:8",
					"tag": "rhel-8-including-unpatched"
				}
			]
		},
		{
			"content": {
				"id": "CVE-2020-36242",
				"severity": [
					{
						"type": "vendor",
						"source": "secalert@redhat.com",
						"vendor": "moderate"
					},
					{
						"type": "cvss_v31",
						"source": "secalert@redhat.com",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
							"base_score": 8.2,
							"base_severity": "HIGH",
							"temporal_score": 8.2,
							"temporal_severity": "HIGH",
							"environmental_score": 8.2,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "secalert@redhat.com",
						"cwe": [
							"CWE-190->CWE-119"
						]
					}
				],
				"references": [
					{
						"source": "secalert@redhat.com",
						"url": "https://access.redhat.com/security/cve/CVE-2020-36242"
					}
				],
				"published": "2020-12-09T00:00:00Z"
			},
			"segments": [
				{
					"ecosystem": "redhat:8",
					"tag": "rhel-8-including-unpatched"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "redhat:8",
			"conditions": [
				{
					"criteria": {
						"operator": "AND",
						"criterions": [
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"type": "binary",
										"binary": {
											"name": "python3-cryptography",
											"architectures": [
												"aarch64",
												"ppc64le",
												"s390x",
												"x86_64"
											]
										}
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:3.2.1-4.el8"
											}
										],
										"fixed": [
											"0:3.2.1-4.el8"
										]
									}
								}
							}
						]
					},
					"tag": "rhel-8-including-unpatched"
				}
			]
		}
	],
	"data_source": {
		"id": "redhat-ovalv2",
		"raws": [
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/definitions/oval:com.redhat.rhsa:def:20211608.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/objects/rpminfo_object/oval:com.redhat.cve:obj:202036242002.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/states/rpminfo_state/oval:com.redhat.rhsa:ste:20211608001.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/tests/rpminfo_test/oval:com.redhat.cve:tst:202036242004.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/tests/rpminfo_test/oval:com.redhat.rhsa:tst:20211608001.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/tests/rpmverifyfile_test/oval:com.redhat.cve:tst:20052541003.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/tests/rpmverifyfile_test/oval:com.redhat.cve:tst:20052541004.json",
			"vuls-data-raw-redhat-ovalv2/8/rhel-8-including-unpatched/tests/rpmverifyfile_test/oval:com.redhat.rhba:tst:20191992004.json",
			"vuls-data-raw-redhat-repository-to-cpe/repository-to-cpe.json"
		]
	}
}
